### ISSUE TITLE
Add snap tag to readme file

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/Security-Bear#21]
We need to add the snap store tag with the link to the readme file as it gives add value to it.

[![Snapcraft](https://img.shields.io/badge/snap-install-82BEA0?style=flat&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAAfVQTFRFAAAAg7+igr+igr+h/1Es+mNA+mND+mM/gr+gg7+hc7KPgcCi/wAA+GRBfruif7Sbgr6h+mVC+mJAgsChfMWpgb6hgrexg7+igr+hgr+hhL+jgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+heMao/0sn/Fw5gr+hgr+hgr+hgr+hgr+hgcCizYZl+2I//GE++mNA+mNA+mNA+mNA+mNAgcCfgr+hgr+hgr+hg76gl6+Q04Fg+GVC/GI/+mNA+mNAgr+hgr+hgr+hgr+hgMGjibqbvJJy8WpH+mNA+mNAgr+hgMCjhL6g1IFf+2I/+mNA+mNA+mNA+mNAgr+hgr+hgr+hdsmr+mNA+mNA+mNA+mNAgr+hgr+h+mNA+mNA+mNAgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+h+mNAgcCi////z300sQAAAKN0Uk5TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCAEBOnI3CQbiuHMrBQRv9OasZyRu8v3gpFscAmrv+9eZTxUBAQEDYOn30GAlZ5GZl5aYVQFW5aWippK99NUgUOSmyeOukqnneE70p0V+1P7ZJUznWgMcZL13R9sPLwZA001IhM7KEsCCqa1oi3AnHc+8GH3SPCg2jTM56DGhzEnHLgy2wSqzJRZ7GyXhzTUAAAABYktHRKa3sBuVAAAACXBIWXMAAOw4AADsOAFxK8o4AAABWklEQVQ4y2NgoBgwiktIMuFVICUtIyvHjEcFs7yMgqKSsgpuNcyqauqLNTS1tFWZcarQ0V28WE/fwNDImBmHChPTxUBgZm5haWVtY8vCiqHCzt5hMRg4Ojm7uLq5e3h6enp5s7HDVXD4+PpBVCz2DwgMCg5ZAgShYUgmcXKFR0AUREYtjY6JjYsHqkhgRVLBzJ0YAVUAJJKSU1LT0jMykR3DzJylAFeQnZPLk5dfUMiLooKvqBiqIMKSX4BBUKiktAzFP8IC5RVgBRGVzFjDQ4S5qrpmcWRtNg55Bua6+ogGp8amcBzyHMzNZosVWlrbcIQ3A3N7B9CNnV04o0y0Gyjf0yuMU0Ef0JMd/cy4khez5ITFi2smMuNMN8yTJi+umYJHXn7q4ml45BmYp+vOmMksjFt+1uw5c/HJM9vPm88sxoBbwYKF2viyBgPz/EV45RmYjZnxK6AEAACJjG4Guv8uAwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMC0wMS0xMFQxNjozNDozOSswMDowMOoslwkAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjAtMDEtMTBUMTY6MzQ6MzkrMDA6MDCbcS+1AAAARnRFWHRzb2Z0d2FyZQBJbWFnZU1hZ2ljayA2LjcuOC05IDIwMTktMDItMDEgUTE2IGh0dHA6Ly93d3cuaW1hZ2VtYWdpY2sub3JnQXviyAAAABh0RVh0VGh1bWI6OkRvY3VtZW50OjpQYWdlcwAxp/+7LwAAABh0RVh0VGh1bWI6OkltYWdlOjpoZWlnaHQANTEywNBQUQAAABd0RVh0VGh1bWI6OkltYWdlOjpXaWR0aAA1MTIcfAPcAAAAGXRFWHRUaHVtYjo6TWltZXR5cGUAaW1hZ2UvcG5nP7JWTgAAABd0RVh0VGh1bWI6Ok1UaW1lADE1Nzg2NzQwNznfLoLhAAAAE3RFWHRUaHVtYjo6U2l6ZQAxNS44S0JCBxRz5QAAAE90RVh0VGh1bWI6OlVSSQBmaWxlOi8vLi91cGxvYWRzLzU2LzhidnMzYVYvMjEwNy9maWxlX3R5cGVfc25hcGNyYWZ0X2ljb25fMTMwMTYwLnBuZ0uIQNAAAAAASUVORK5CYII=)](https://snapcraft.io/security-bear)

Code to use:
`[![Snapcraft](https://img.shields.io/badge/snap-install-82BEA0?style=flat&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAAfVQTFRFAAAAg7+igr+igr+h/1Es+mNA+mND+mM/gr+gg7+hc7KPgcCi/wAA+GRBfruif7Sbgr6h+mVC+mJAgsChfMWpgb6hgrexg7+igr+hgr+hhL+jgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+heMao/0sn/Fw5gr+hgr+hgr+hgr+hgr+hgcCizYZl+2I//GE++mNA+mNA+mNA+mNA+mNAgcCfgr+hgr+hgr+hg76gl6+Q04Fg+GVC/GI/+mNA+mNAgr+hgr+hgr+hgr+hgMGjibqbvJJy8WpH+mNA+mNAgr+hgMCjhL6g1IFf+2I/+mNA+mNA+mNA+mNAgr+hgr+hgr+hdsmr+mNA+mNA+mNA+mNAgr+hgr+h+mNA+mNA+mNAgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+hgr+h+mNAgcCi////z300sQAAAKN0Uk5TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCAEBOnI3CQbiuHMrBQRv9OasZyRu8v3gpFscAmrv+9eZTxUBAQEDYOn30GAlZ5GZl5aYVQFW5aWippK99NUgUOSmyeOukqnneE70p0V+1P7ZJUznWgMcZL13R9sPLwZA001IhM7KEsCCqa1oi3AnHc+8GH3SPCg2jTM56DGhzEnHLgy2wSqzJRZ7GyXhzTUAAAABYktHRKa3sBuVAAAACXBIWXMAAOw4AADsOAFxK8o4AAABWklEQVQ4y2NgoBgwiktIMuFVICUtIyvHjEcFs7yMgqKSsgpuNcyqauqLNTS1tFWZcarQ0V28WE/fwNDImBmHChPTxUBgZm5haWVtY8vCiqHCzt5hMRg4Ojm7uLq5e3h6enp5s7HDVXD4+PpBVCz2DwgMCg5ZAgShYUgmcXKFR0AUREYtjY6JjYsHqkhgRVLBzJ0YAVUAJJKSU1LT0jMykR3DzJylAFeQnZPLk5dfUMiLooKvqBiqIMKSX4BBUKiktAzFP8IC5RVgBRGVzFjDQ4S5qrpmcWRtNg55Bua6+ogGp8amcBzyHMzNZosVWlrbcIQ3A3N7B9CNnV04o0y0Gyjf0yuMU0Ef0JMd/cy4khez5ITFi2smMuNMN8yTJi+umYJHXn7q4ml45BmYp+vOmMksjFt+1uw5c/HJM9vPm88sxoBbwYKF2viyBgPz/EV45RmYjZnxK6AEAACJjG4Guv8uAwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMC0wMS0xMFQxNjozNDozOSswMDowMOoslwkAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjAtMDEtMTBUMTY6MzQ6MzkrMDA6MDCbcS+1AAAARnRFWHRzb2Z0d2FyZQBJbWFnZU1hZ2ljayA2LjcuOC05IDIwMTktMDItMDEgUTE2IGh0dHA6Ly93d3cuaW1hZ2VtYWdpY2sub3JnQXviyAAAABh0RVh0VGh1bWI6OkRvY3VtZW50OjpQYWdlcwAxp/+7LwAAABh0RVh0VGh1bWI6OkltYWdlOjpoZWlnaHQANTEywNBQUQAAABd0RVh0VGh1bWI6OkltYWdlOjpXaWR0aAA1MTIcfAPcAAAAGXRFWHRUaHVtYjo6TWltZXR5cGUAaW1hZ2UvcG5nP7JWTgAAABd0RVh0VGh1bWI6Ok1UaW1lADE1Nzg2NzQwNznfLoLhAAAAE3RFWHRUaHVtYjo6U2l6ZQAxNS44S0JCBxRz5QAAAE90RVh0VGh1bWI6OlVSSQBmaWxlOi8vLi91cGxvYWRzLzU2LzhidnMzYVYvMjEwNy9maWxlX3R5cGVfc25hcGNyYWZ0X2ljb25fMTMwMTYwLnBuZ0uIQNAAAAAASUVORK5CYII=)](https://snapcraft.io/security-bear)`

**Comment by Tamir198** [comment]
Could you assign me that issue?

**Comment by guyluz11** [comment]
Sure

**Comment by guyluz11** [comment]
Now in dev branch, thanks @Tamir198.

Will now close this issue
