### ISSUE TITLE
Update logo in readme

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/Security-Bear#7]
Please update the logo in readme file
 to this new one

<img src="https://user-images.githubusercontent.com/9304740/97423649-3ab85300-1918-11eb-8c2e-50ce0445c457.png" height="300">

`https://user-images.githubusercontent.com/9304740/97423649-3ab85300-1918-11eb-8c2e-50ce0445c457.png`

**Comment by ameyanrd** [comment]
Hi, can you assign this issue to me? Thanks!

**Comment by guyluz11** [comment]
Thanks for the pr @ameyanrd 
Will now close the issue.
